// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "isitenonvisual.h"

/////////////////////////////////////////////////////////////////////////////
// CiSiteNonVisual

IMPLEMENT_DYNCREATE(CiSiteNonVisual, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CiSiteNonVisual properties

CString CiSiteNonVisual::GetISyntaxServerIP()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetISyntaxServerIP(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CiSiteNonVisual::GetISyntaxServerPort()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetISyntaxServerPort(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CiSiteNonVisual::GetImageSuiteURL()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetImageSuiteURL(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CiSiteNonVisual::GetImageSuiteDSN()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetImageSuiteDSN(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

long CiSiteNonVisual::GetCacheSizeMB()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetCacheSizeMB(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

CString CiSiteNonVisual::GetWorkstationLocation()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetWorkstationLocation(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

CString CiSiteNonVisual::GetSecurityCodes()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetSecurityCodes(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

BOOL CiSiteNonVisual::GetInitialized()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

CString CiSiteNonVisual::GetOptions()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetOptions(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

CString CiSiteNonVisual::GetFailoveriSyntaxServerIP()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteNonVisual::SetFailoveriSyntaxServerIP(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CiSiteNonVisual operations

BOOL CiSiteNonVisual::Initialize()
{
	BOOL result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CiSiteNonVisual::Login(LPCTSTR UserName, LPCTSTR Password, LPCTSTR AuthSource, LPCTSTR Token, LPCTSTR Mnemonic)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		UserName, Password, AuthSource, Token, Mnemonic);
	return result;
}

BOOL CiSiteNonVisual::Logout()
{
	BOOL result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CiSiteNonVisual::Query(LPCTSTR QueryStr, LPCTSTR Type, long MaxResults)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		QueryStr, Type, MaxResults);
	return result;
}

long CiSiteNonVisual::Exists(LPCTSTR QueryStr, LPCTSTR Type)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		QueryStr, Type);
	return result;
}

CString CiSiteNonVisual::FindPatient(LPCTSTR PatientID, LPCTSTR Organziation)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		PatientID, Organziation);
	return result;
}

CString CiSiteNonVisual::FindExam(LPCTSTR Accession, LPCTSTR PatientID, LPCTSTR Organization)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Accession, PatientID, Organization);
	return result;
}

CString CiSiteNonVisual::GetReportData(LPCTSTR IntPatientID, LPCTSTR IntExamID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		IntPatientID, IntExamID);
	return result;
}

long CiSiteNonVisual::GetLastErrorCode()
{
	long result;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CiSiteNonVisual::FindStudy(LPCTSTR StudyUID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		StudyUID);
	return result;
}

VARIANT CiSiteNonVisual::InternalExecute(LPCTSTR FnName, LPCTSTR Param1, LPCTSTR Param2, LPCTSTR Param3)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		FnName, Param1, Param2, Param3);
	return result;
}

BOOL CiSiteNonVisual::ChangePassword(LPCTSTR OldPassword, LPCTSTR NewPassword)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		OldPassword, NewPassword);
	return result;
}

CString CiSiteNonVisual::GetCurrentUser()
{
	CString result;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CiSiteNonVisual::LockExam(LPCTSTR IntExamID, long Enable)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		IntExamID, Enable);
	return result;
}

BOOL CiSiteNonVisual::MarkExamRead(LPCTSTR IntExamID, long bMarkReadFlg)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		IntExamID, bMarkReadFlg);
	return result;
}

BOOL CiSiteNonVisual::SetPreference(LPCTSTR Name, LPCTSTR Type, LPCTSTR Data)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, Type, Data);
	return result;
}

CString CiSiteNonVisual::GetPreference(LPCTSTR Name, LPCTSTR Type)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Name, Type);
	return result;
}

CString CiSiteNonVisual::GetWorkstationLocations()
{
	CString result;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CiSiteNonVisual::GetAuthSources()
{
	CString result;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CiSiteNonVisual::EmergencyAccessLogin(LPCTSTR UserName, LPCTSTR Password, LPCTSTR AuthSource, LPCTSTR Token, LPCTSTR Mnemonic)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		UserName, Password, AuthSource, Token, Mnemonic);
	return result;
}

CString CiSiteNonVisual::GetCachedExams()
{
	CString result;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CiSiteNonVisual::CacheExam(LPCTSTR bstrIntExamID, LPCTSTR bstrIntExcpID, BOOL bLockExam)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bstrIntExamID, bstrIntExcpID, bLockExam);
	return result;
}

BOOL CiSiteNonVisual::ResumeCachingExam(LPCTSTR bstrIntExamID, LPCTSTR bstrIntExcpID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bstrIntExamID, bstrIntExcpID);
	return result;
}

BOOL CiSiteNonVisual::CancelExamCaching(LPCTSTR bstrIntExamID, LPCTSTR bstrIntExcpID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bstrIntExamID, bstrIntExcpID);
	return result;
}

BOOL CiSiteNonVisual::DeleteCachedExam(LPCTSTR bstrIntExamID, LPCTSTR bstrIntExcpID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bstrIntExamID, bstrIntExcpID);
	return result;
}

void CiSiteNonVisual::DisableAutologout(BOOL bDisable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bDisable);
}

BOOL CiSiteNonVisual::ShowDebugWindow()
{
	BOOL result;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CiSiteNonVisual::GetFoldersAndFiltersXML()
{
	CString result;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CiSiteNonVisual::GetVersion()
{
	CString result;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CiSiteNonVisual::FindException(LPCTSTR StudyUID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		StudyUID);
	return result;
}

CString CiSiteNonVisual::QueryEx(LPCTSTR Query, LPCTSTR Type, LPCTSTR PrimarySort, long PrimarySortDir, LPCTSTR SecondarySort, long SecondSortDir, long MaxResults)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4 VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Query, Type, PrimarySort, PrimarySortDir, SecondarySort, SecondSortDir, MaxResults);
	return result;
}

VARIANT CiSiteNonVisual::GetImageHeaders(LPCTSTR bstrStudyID, LPCTSTR bstrSeriesID, LPCTSTR bstrImageID)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		bstrStudyID, bstrSeriesID, bstrImageID);
	return result;
}

VARIANT CiSiteNonVisual::GetViewPixels(LPCTSTR bstrStudyID, LPCTSTR bstrSeriesID, LPCTSTR bstrImageID, long nLeft, long nTop, long nRight, long nBottom, long nCompressionRatio)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		bstrStudyID, bstrSeriesID, bstrImageID, nLeft, nTop, nRight, nBottom, nCompressionRatio);
	return result;
}

void CiSiteNonVisual::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
