// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "isiteenterprise1.h"

/////////////////////////////////////////////////////////////////////////////
// CiSiteEnterprise1

IMPLEMENT_DYNCREATE(CiSiteEnterprise1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CiSiteEnterprise1 properties

CString CiSiteEnterprise1::GetHelpPath()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteEnterprise1::SetHelpPath(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

BOOL CiSiteEnterprise1::GetInitialized()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

CString CiSiteEnterprise1::GetOptions()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteEnterprise1::SetOptions(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CiSiteEnterprise1::GetBrowserPageName()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteEnterprise1::SetBrowserPageName(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CiSiteEnterprise1::GetBrowserPageURL()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteEnterprise1::SetBrowserPageURL(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CiSiteEnterprise1::GetCCOWOptions()
{
	CString result;
	GetProperty(0x46, VT_BSTR, (void*)&result);
	return result;
}

void CiSiteEnterprise1::SetCCOWOptions(LPCTSTR propVal)
{
	SetProperty(0x46, VT_BSTR, propVal);
}

BOOL CiSiteEnterprise1::GetCCOWEnabled()
{
	BOOL result;
	GetProperty(0x47, VT_BOOL, (void*)&result);
	return result;
}

void CiSiteEnterprise1::SetCCOWEnabled(BOOL propVal)
{
	SetProperty(0x47, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CiSiteEnterprise1 operations

BOOL CiSiteEnterprise1::Reset()
{
	BOOL result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CiSiteEnterprise1::RemoveViewMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterViewMenuItem(LPCTSTR Name, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::CopyToClipboard(LPCTSTR WndID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WndID);
	return result;
}

CString CiSiteEnterprise1::GetWindowContext(LPCTSTR WndID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WndID);
	return result;
}

BOOL CiSiteEnterprise1::SetWindowImage(LPCTSTR WindowID, LPCTSTR ImageUID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WindowID, ImageUID);
	return result;
}

BOOL CiSiteEnterprise1::SetWindowView(LPCTSTR WindowID, float ZoomFactor, short Top, short Left, long WindowWIdth, long WindowCenter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_R4 VTS_I2 VTS_I2 VTS_I4 VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WindowID, ZoomFactor, Top, Left, WindowWIdth, WindowCenter);
	return result;
}

CString CiSiteEnterprise1::GetStaticWindowInfo(LPCTSTR WindowID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WindowID);
	return result;
}

CString CiSiteEnterprise1::GetActiveWindow()
{
	CString result;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CiSiteEnterprise1::AddViewMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::Initialize(LPUNKNOWN Session)
{
	BOOL result;
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Session);
	return result;
}

BOOL CiSiteEnterprise1::ShowClinicalExamNotes(LPCTSTR CanvasPageID, LPCTSTR ShelfID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		CanvasPageID, ShelfID);
	return result;
}

BOOL CiSiteEnterprise1::SetShelfDragBarColor(LPCTSTR ShelfID, long Color)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ShelfID, Color);
	return result;
}

BOOL CiSiteEnterprise1::AddExamMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::RemoveExamMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterExamMenuItem(LPCTSTR Name, LPCTSTR InsertAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, InsertAfter);
	return result;
}

CString CiSiteEnterprise1::CreatePopup(LPCTSTR WindowID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WindowID);
	return result;
}

BOOL CiSiteEnterprise1::DestroyPopup(LPCTSTR WindowID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WindowID);
	return result;
}

VARIANT CiSiteEnterprise1::InternalExecute(LPCTSTR FuncName, LPCTSTR Param1, LPCTSTR Param2, LPCTSTR Param3)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		FuncName, Param1, Param2, Param3);
	return result;
}

CString CiSiteEnterprise1::GetDICOMValue(LPCTSTR WindowID, LPCTSTR DICOMTag)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WindowID, DICOMTag);
	return result;
}

BOOL CiSiteEnterprise1::EnablePreferenceApplyButton()
{
	BOOL result;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CiSiteEnterprise1::GetDICOMInstance(LPCTSTR WindowID, LPCTSTR ImageUID, VARIANT* Buffer)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_PVARIANT;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		WindowID, ImageUID, Buffer);
	return result;
}

CString CiSiteEnterprise1::OpenCanvasPage(LPCTSTR IntExamID, LPCTSTR IntExceptionID, BOOL Reveal, BOOL Lock, BOOL OpenNew)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		IntExamID, IntExceptionID, Reveal, Lock, OpenNew);
	return result;
}

CString CiSiteEnterprise1::ListCanvasPages()
{
	CString result;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CiSiteEnterprise1::GetCanvasPageStatus(LPCTSTR CanvasPageID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CanvasPageID);
	return result;
}

BOOL CiSiteEnterprise1::CloseCanvasPage(LPCTSTR CanvasPageID, BOOL DiscardChanges)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		CanvasPageID, DiscardChanges);
	return result;
}

CString CiSiteEnterprise1::OpenShelf(LPCTSTR CanvasPageID, LPCTSTR IntExamID, LPCTSTR IntExceptionID, BOOL Reveal)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BOOL;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CanvasPageID, IntExamID, IntExceptionID, Reveal);
	return result;
}

CString CiSiteEnterprise1::ListShelfs(LPCTSTR CanvasPageID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CanvasPageID);
	return result;
}

CString CiSiteEnterprise1::GetShelfStatus(LPCTSTR ShelfID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		ShelfID);
	return result;
}

BOOL CiSiteEnterprise1::CloseShelf(LPCTSTR ShelfID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ShelfID);
	return result;
}

BOOL CiSiteEnterprise1::AddShelfMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::RemoveShelfMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterShelfMenuItem(LPCTSTR Name, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::SetShelfURL(LPCTSTR ShelfID, LPCTSTR URL, long ReportWidth)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ShelfID, URL, ReportWidth);
	return result;
}

CString CiSiteEnterprise1::GetShelfWindowIDs(LPCTSTR ShelfID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		ShelfID);
	return result;
}

BOOL CiSiteEnterprise1::SetActivePage(LPCTSTR Name, LPCTSTR Type)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, Type);
	return result;
}

BOOL CiSiteEnterprise1::AddPreferencePage(LPCTSTR Name, LPCTSTR URL, LPCTSTR Type)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, URL, Type);
	return result;
}

BOOL CiSiteEnterprise1::DisplayMediaExportPage(LPCTSTR InternalExamIds, long RemoveAllExams)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		InternalExamIds, RemoveAllExams);
	return result;
}

long CiSiteEnterprise1::MessageBox(LPCTSTR Msg, long nType)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Msg, nType);
	return result;
}

CString CiSiteEnterprise1::FindShelfID(LPCTSTR IntExamID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		IntExamID);
	return result;
}

CString CiSiteEnterprise1::FindCanvasPageID(LPCTSTR IntPatientID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		IntPatientID);
	return result;
}

CString CiSiteEnterprise1::ListMediaExportExams()
{
	CString result;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL CiSiteEnterprise1::AddViewSubMenu(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::AddViewSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterViewSubMenu(LPCTSTR Name, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterViewSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::AddExamSubMenu(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::AddExamSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterExamSubMenu(LPCTSTR Name, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterExamSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::AddShelfSubMenu(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::AddShelfSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterShelfSubMenu(LPCTSTR Name, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterShelfSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::AddShelfButton(LPCTSTR pszShelfID, LPCTSTR pszButtonID, LPCTSTR pszBitMap, LPCTSTR pszToolTip)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		pszShelfID, pszButtonID, pszBitMap, pszToolTip);
	return result;
}

BOOL CiSiteEnterprise1::ShowPreferenceDialog()
{
	BOOL result;
	InvokeHelper(0x3d, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CiSiteEnterprise1::AddTimelineSubMenu(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::AddTimelineSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterTimelineSubMenu(LPCTSTR Name, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x40, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterTimelineSubMenuItem(LPCTSTR Name, LPCTSTR SubMenuName, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x41, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, SubMenuName, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::AddTimelineMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x42, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::RemoveTimelineMenuItem(LPCTSTR Name)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x43, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name);
	return result;
}

BOOL CiSiteEnterprise1::InsertAfterTimelineMenuItem(LPCTSTR Name, LPCTSTR NameAfter)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x44, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Name, NameAfter);
	return result;
}

BOOL CiSiteEnterprise1::DisplayiExportQueue()
{
	BOOL result;
	InvokeHelper(0x45, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CiSiteEnterprise1::CopyImageToClipboard(LPCTSTR WndID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		WndID);
	return result;
}

CString CiSiteEnterprise1::SavePresentationState(LPCTSTR bstrShelfID, LPCTSTR pszDesc, long nType)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		bstrShelfID, pszDesc, nType);
	return result;
}

BOOL CiSiteEnterprise1::LoadPresentationState(LPCTSTR bstrShelfID, LPCTSTR bstrName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bstrShelfID, bstrName);
	return result;
}

BOOL CiSiteEnterprise1::DeleteAnnotation(LPCTSTR bstrWindowID, LPCTSTR bstrToken)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bstrWindowID, bstrToken);
	return result;
}

BOOL CiSiteEnterprise1::WriteDICOMInstance(LPCTSTR bstrWindowID, LPCTSTR bstrImageUID, LPCTSTR bstrPathName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bstrWindowID, bstrImageUID, bstrPathName);
	return result;
}

LPDISPATCH CiSiteEnterprise1::CopyWindowToPicture(LPCTSTR bstrWindowID, long nLeft, long nTop, long nRight, long nBottom)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		bstrWindowID, nLeft, nTop, nRight, nBottom);
	return result;
}

LPDISPATCH CiSiteEnterprise1::CopyImageToPicture(LPCTSTR bstrWindowID, long nLeft, long nTop, long nRight, long nBottom)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		bstrWindowID, nLeft, nTop, nRight, nBottom);
	return result;
}

void CiSiteEnterprise1::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
