#if !defined(AFX_ISITEIMAGE_H__B829A55F_EF54_41A4_B29E_DE7599ADE410__INCLUDED_)
#define AFX_ISITEIMAGE_H__B829A55F_EF54_41A4_B29E_DE7599ADE410__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CiSiteImage wrapper class

class CiSiteImage : public CWnd
{
protected:
	DECLARE_DYNCREATE(CiSiteImage)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x11f110a2, 0xbf9d, 0x4795, { 0x9c, 0xe3, 0x6, 0x77, 0x40, 0x38, 0xa, 0x3f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetInteractive();
	void SetInteractive(BOOL);
	BOOL GetInitialized();

// Operations
public:
	BOOL Initialize(LPUNKNOWN Session);
	BOOL DisplayImage(LPCTSTR StudyUID, LPCTSTR SeriesUID, LPCTSTR ImageUID);
	BOOL DisplayStack(LPCTSTR StudyUID, LPCTSTR SeriesUID);
	BOOL CloseDisplay();
	CString GetWindowContext();
	BOOL SetWindowImage(LPCTSTR ImageUID);
	BOOL SetWindowView(short ZoomLevel, short Top, short Left, long WindowWIdth, long WindowCenter);
	CString GetStaticWindowInfo();
	BOOL SetRotationOrientation(BOOL flip, long rotate);
	CString GetDICOMValue(LPCTSTR DICOMTag);
	long GetDICOMInstance(LPCTSTR ImageUID, VARIANT* psaData);
	BOOL WriteDICOMInstance(LPCTSTR bstrWindowID, LPCTSTR bstrImageUID, LPCTSTR bstrPathName);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ISITEIMAGE_H__B829A55F_EF54_41A4_B29E_DE7599ADE410__INCLUDED_)
